---
- hosts: testing
  become: yes

  vars_files:
    - vars/agent_token.yml
  
  handlers:
    - import_tasks: "handlers/handlers.yml" 

  pre_tasks:
  - name: Update apt cache
    apt: update_cache=yes cache_valid_time=3600

  - name: Raspberry Pi cluster prerequisites
    import_tasks: "tasks/raspberry.yml"
    when: inventory_hostname in groups['cluster']

  tasks:
  - name: Common tasks for server and agent
    import_tasks: "tasks/common.yml"

  - name: Server tasks
    import_tasks: "tasks/server.yml"
    when: inventory_hostname in groups['server']

  - name: Agent tasks
    import_tasks: "tasks/agent.yml"
    when: inventory_hostname in groups['agent']


  

