---
- name: Setting eth0 interface IP address
  community.general.nmcli:
    type: ethernet
    conn_name: "{{ iface }}"
    ip4: "{{ ip }}/24"
    state: present

- name: Enable cgroups
  replace:
    path: /boot/cmdline.txt
    regexp: "CH$"
    replace: "CH cgroup_memory=1 cgroup_enable=memory"
    backup: true
  notify: Reboot